### ISSUE TITLE
Validation of dropbox-cli fails

### ISSUE THREAD

**Issue by LorenzoBettini** [frealgagu/archlinux.dropbox-cli#5]
This happens again https://aur.archlinux.org/packages/dropbox-cli#comment-904397

**Comment by frealgagu** [comment]
Each time checksum fails please flag the package as outdated. They replace the file upstreaming so is necessary to fix the version and checksum.

**Comment by LorenzoBettini** [comment]
> Each time checksum fails please flag the package as outdated. They replace the file upstreaming so is necessary to fix the version and checksum.

I'm not sure I understand: is it something we (consumers) can do?

**Comment by frealgagu** [comment]
Just flag the package in AUR to me know that it is not up to date.
